version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    # Only expose ports if you want direct access; otherwise, comment out
    # ports:
    #   - "1883:1883"
    #   - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqttnet

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate -url http://mosquitto:9001
    depends_on:
      - mosquitto
    networks:
      - mqttnet

networks:
  mqttnet:
    driver: bridge
